language: java
dist: trusty

services:
  - docker

jdk:
  - oraclejdk8

install: true

jobs:
  include:
    - stage: Build SNAPSHOT
      script:
      - export TRANSFORMER_VERSION=$(./gradlew -q printVersion -Prelease.stage=SNAPSHOT)      
      - ./gradlew snapshot      
      - ./packaging/container/docker_build.sh

deploy:
  skip_cleanup: true  
  provider: script
  script: bash packaging/container/docker_push.sh
  on:
    all_branches: true
    
after_success:
  - bash <(curl -s https://codecov.io/bash)

